import Link from "next/link";

export default function PartnershipFirmContent() {
  return (
    <article className="prose prose-lg text-muted max-w-none prose-headings:font-heading prose-headings:text-primary prose-headings:font-semibold">
      <div className="not-prose mb-8 p-4 rounded-xl bg-muted/10 border border-muted/25 text-sm text-muted leading-relaxed">
        <strong className="text-primary">Disclaimer:</strong> The information provided on this page is for general awareness only and may be updated as the Government of India revises the Indian Partnership Act or related regulations. Please refer to the{" "}
        <a href="https://www.indiacode.nic.in" target="_blank" rel="noopener noreferrer" className="text-accent underline underline-offset-2 hover:text-primary transition-colors">official India Code portal</a>{" "}
        or your respective State Registrar of Firms for the most current and accurate requirements.
      </div>

      <h2 className="text-2xl mt-10 mb-4">What is a Partnership Firm?</h2>
      <p className="leading-relaxed">
        In India, partnerships are regulated under the <strong className="text-primary">Indian Partnership Act, 1932</strong>. A partnership arises when two or more individuals come together and agree to share the profits generated by a business — operated jointly or by any one or more acting on behalf of the rest. To establish a partnership firm, at least two partners are required.
      </p>
      <p className="leading-relaxed">
        The formal written agreement outlining the roles, responsibilities, profit-sharing, and operational terms is known as a <strong className="text-primary">Partnership Deed</strong>. While verbal agreements are legally permissible, a written deed is strongly recommended to avoid disputes.
      </p>

      <h2 className="text-2xl mt-10 mb-4">Types of Partnership Firms</h2>

      <h3 className="text-xl mt-6 mb-3">Registered Partnership Firm</h3>
      <p className="leading-relaxed">
        A firm formally registered with the Registrar of Firms under the Indian Partnership Act, 1932. Registration is not mandatory but is highly recommended. A registered firm has the right to file a case against partners or third parties for enforcing contractual rights, has improved credibility with banks and clients, and can participate in tenders and government contracts.
      </p>

      <h3 className="text-xl mt-6 mb-3">Unregistered Partnership Firm</h3>
      <p className="leading-relaxed">
        A firm that has not been registered with the Registrar of Firms. While legally valid and able to conduct business, it cannot sue any partner or a third party to enforce rights arising from the partnership agreement, which can severely impact the firm&apos;s ability to recover dues or protect its business interests.
      </p>

      <h2 className="text-2xl mt-10 mb-4">Key Features of a Partnership Firm</h2>
      <ul className="list-disc pl-6 space-y-1 my-4">
        <li><strong className="text-primary">Not a Separate Legal Entity</strong> – Partners are personally liable for the firm&apos;s debts and obligations.</li>
        <li><strong className="text-primary">Established by Agreement</strong> – Formed through a written or verbal agreement, usually a Partnership Deed.</li>
        <li><strong className="text-primary">Profit and Loss Sharing</strong> – All profits and losses are shared in the ratio specified in the deed.</li>
        <li><strong className="text-primary">Joint Management</strong> – Unless stated otherwise, each partner has the right to participate in decision-making.</li>
        <li><strong className="text-primary">Tax Treatment</strong> – Partnership firms are not taxed as a separate entity; income is divided among partners who declare it individually.</li>
        <li><strong className="text-primary">Transfer Restrictions</strong> – Ownership cannot be transferred freely; all partners must approve any change.</li>
      </ul>

      <h2 className="text-2xl mt-10 mb-4">Advantages of Registering Your Partnership Firm</h2>
      <ul className="list-disc pl-6 space-y-2 my-4">
        <li><strong className="text-primary">Legal Recognition</strong> – Can enter contracts, own property, and pursue legal action in its name.</li>
        <li><strong className="text-primary">Credibility</strong> – Viewed as more trustworthy by clients, banks, and suppliers.</li>
        <li><strong className="text-primary">Access to Financing</strong> – Financial institutions are more likely to extend credit and loans to registered firms.</li>
        <li><strong className="text-primary">Business Continuity</strong> – Even if a partner exits or passes away, a registered partnership can continue.</li>
        <li><strong className="text-primary">Tax Efficiency</strong> – Partner remuneration is treated as an allowable expense, reducing taxable income.</li>
        <li><strong className="text-primary">Structured Dispute Resolution</strong> – Registered partnerships follow legal procedures for resolving internal conflicts.</li>
        <li><strong className="text-primary">Scalability</strong> – Addition of new partners is easier when the firm is officially recognised.</li>
      </ul>

      <h2 className="text-2xl mt-10 mb-4">Documents Required</h2>
      <ul className="list-disc pl-6 space-y-1 my-4">
        <li>Partnership Deed (signed by all partners on judicial stamp paper)</li>
        <li>PAN cards of all partners</li>
        <li>Address proof of all partners and the place of business</li>
        <li>Passport-size photographs of all partners</li>
        <li>Utility bill as address proof for the office</li>
        <li>Rental agreement (if the office is on rent)</li>
      </ul>

      <div className="mt-12 p-6 rounded-2xl bg-primary/5 border border-primary/10">
        <h2 className="text-xl font-heading font-semibold text-primary mb-3">Register Your Partnership Firm — Expert Assistance Across India</h2>
        <p className="leading-relaxed text-muted mb-4">
          HETAL J SHAH &amp; Co. offers end-to-end partnership firm registration services across India — from drafting the Partnership Deed to handling filings, PAN/TAN applications, and ongoing compliance.
        </p>
        <ul className="list-disc pl-6 space-y-1 text-muted mb-6">
          <li>Drafting of a legally compliant Partnership Deed</li>
          <li>Registration with the Registrar of Firms</li>
          <li>PAN &amp; TAN application and assistance</li>
          <li>Regulatory compliance, return filing, and statutory record maintenance</li>
          <li>Expert advice on partner structure, profit-sharing, and business objectives</li>
        </ul>
        <div className="flex flex-wrap gap-4">
          <Link href="/#contact" className="inline-flex items-center px-6 py-3 bg-primary text-white font-medium rounded-lg hover:bg-accent hover:text-primary transition-colors focus:outline-none focus:ring-2 focus:ring-accent focus:ring-offset-2">Get in touch</Link>
          <Link href="/services" className="inline-flex items-center px-6 py-3 border border-muted/30 text-primary font-medium rounded-lg hover:border-accent hover:text-accent transition-colors focus:outline-none focus:ring-2 focus:ring-accent focus:ring-offset-2">View all services</Link>
        </div>
      </div>
    </article>
  );
}
